name: 'Docker Integration Tests Action'
description: 'Get started with Container actions'
author: 'GitHub'
icon: alert-circle
inputs: 
  myInput:
    description: 'Input to use'
    default: 'world'
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.myInput }}
